### Use "make prefix=/usr" (override prefix=/usr/local in Makefile)
#override_dh_auto_install:
#	dh_auto_install -- prefix=/usr

### Do not install python .pyc .pyo if they exist
#override_dh_install:
#	dh_install --list-missing -X.pyc -X.pyo
