# ref: https://circleci.com/docs/2.0/getting-started
version: 2
jobs:
  build:
    docker:
      - image: debian:unstable
    steps:
      - checkout
      - run:
          name: update and install dependencies
          command: |
              echo "deb http://deb.debian.org/debian unstable main" > /etc/apt/sources.list
              echo "deb-src http://deb.debian.org/debian unstable main" >> /etc/apt/sources.list
              apt-get update -y
              apt-get upgrade -y
              apt-get install eatmydata -y
              eatmydata -- apt-get install debhelper python3 -y
      - run:
          name: build package
          command: |
              dpkg-buildpackage -us -uc
              git clean -xdf
      - run:
          name: make test
          command: |
              make test
              git clean -xdf
      - run:
          make: lib-test
          command: |
              cd lib; make test
              git clean -xdf
