.\" (C) Copyright 2011-2012 Vasudev Kamath <kamathvasudev@gmail.com>
.\"                     and Muneeb Shaikh <iammuneeb@gmail.com>
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.TH dh_makefont 1 2016-01-04 "Debian Project"
.SH NAME
dh_makefont \- Debian Font packaging helper

.SH SYNOPSIS
.B dh_makefont
[\-h, \-\-help] [\-c,\-\-copyright <type>] [\-p,\-\-package <name[_version]>]
[\-\-maint MAINT] [\-u,\-\-upstream UPSTREAMURL]
.I font_folder

.SH DESCRIPTION
.B dh_makefont
is a wrapper for the \fBdh_make\fR command to convert regular font source
packages into one formatted according to the requirements of the Debian
Policy.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display the name, version, available options and authors, and exit
successfully.
.TP
.BR \-c ", " \-\-copyright\  \fIlicense\fR
Use \fIlicense\fR in copyright file for the package. \fIlicense\fR can be
one of apache|artistic|bsd|gpl|gpl2|gpl3|lgpl|lgpl2|lgpl3|x11.
.TP
.BR \-p ", " \-\-package\  \fIname[_version]\fR
Force package name to be \fIname\fR. If \fIname_version\fR is given this will set
version number of package bypassing the directory checking.
.TP
.BR \-\-maint\  maintainer
Ovrride the default name of the mainter from "\fBDebian Fonts Task Force\fR"
to \fImaintainer\fR.  to *Debian Fonts Task Force*. \fImaintainer\fR should be
in the form
.I Maintainer Name <maint.email>
.TP
.BR \-u ", " \-\-upstream\  \fIurl\fR
Set the url from where the fonts were downloaded from to \fIurl\fR.
This url will be used in the following fields:
.I Homepage:
field of the control file and
.I Source:
field of the copyright file
.TP
.BR \-v ", " \-\-version
Show the version number of program and exit.
.TP
.I font_folder
This is the name of the folder in which you have extracted the fonts.
Rules for folder name are same as \fBdh_make\fR. If you didn't give proper
name \fBdh_make\fR will fail.
.SH ENVIRONMENT
The following environment settings are used by \fBdh\_makefont\fR:
.TP
.B DEBEMAIL
Email address to use in control and changelog entries.
.TP
.B DEBFULLNAME
You full name, eg "John Doe" which will appear in the control and changelog
entries.

.SH BUGS
If the package name has a hypen '\-' in it then \fBdh_makefont\fR will mess
up the package naming.
.SH SEE ALSO
.BR dh_make (1), dh (1)
