@PACKAGE@ for Debian

Please edit this to provide information specific to
this @PACKAGE@ Debian package.

    (Automatically generated by debmake Version @DEBMAKEVER@)

 -- @FULLNAME@ <@EMAIL@>  @DATE@
